module.exports = [
  {
    id: 3,
    bpid: 1,
    name: '渠道管理',
    icon: 'api',
    router: '/agent',
  },
  {
    id: 31,
    bpid: 3,
    mpid: 3,
    name: '渠道列表',
    icon: 'database',
    router: '/agent',
  },
  {
    id: 32,
    bpid: 3,
    mpid: 3,
    name: '渠道审核',
    icon: 'database',
    router: '/agent/audit',
  },
  {
    id: 36,
    bpid: 3,
    mpid: 3,
    name: '渠道审核记录',
    icon: 'database',
    router: '/agent/review',
  },
  // {
  //   id: 33,
  //   bpid: 3,
  //   mpid: 3,
  //   name: '员工管理',
  //   icon: '',
  //   router: '/agent/employee',
  // },
  // {
  //   id: 34,
  //   bpid: 3,
  //   mpid: 3,
  //   name: '员工导入',
  //   icon: '',
  //   router: '/agent/employee/import',
  // },
  // {
  //   id: 35,
  //   bpid: 3,
  //   mpid: 3,
  //   name: '物料管理',
  //   icon: '',
  //   router: '/agent/resource',
  // },
  {
    id: 4,
    bpid: 1,
    name: '商户管理',
    icon: 'solution',
    router: '/merchant',
  },
  {
    id: 41,
    bpid: 4,
    mpid: 4,
    name: '商户列表',
    icon: 'database',
    router: '/merchant',
  },
  {
    id: 42,
    bpid: 4,
    mpid: 4,
    name: '商户审核',
    icon: 'database',
    router: '/merchant/audit',
  },
  // {
  //   id: 43,
  //   bpid: 4,
  //   mpid: 4,
  //   name: '子商户迁移',
  //   icon: '',
  //   router: '/merchant/submigrate',
  // },
  // {
  //   id: 44,
  //   bpid: 4,
  //   mpid: 4,
  //   name: '草稿箱',
  //   icon: '',
  //   router: '/merchant/draft',
  // },
  {
    id: 45,
    bpid: 4,
    mpid: 4,
    name: '商户审核记录',
    icon: 'database',
    router: '/merchant/review',
  },
  {
    id: 5,
    bpid: 1,
    name: '交易管理',
    icon: 'database',
    router: '/transaction',
  },
  {
    id: 51,
    bpid: 5,
    mpid: 5,
    name: '数据汇总',
    icon: 'database',
    router: '/transaction/total',
  },
  {
    id: 52,
    bpid: 5,
    mpid: 5,
    name: '订单查询',
    icon: 'database',
    router: '/transaction/flow',
  },
  {
    id: 6,
    bpid: 1,
    name: '结算管理',
    icon: 'wallet',
    router: '/statistic',
  },
  {
    id: 61,
    bpid: 6,
    mpid: 6,
    name: '商户手续费统计',
    icon: 'database',
    router: '/statistic/merchant',
  },
  {
    id: 62,
    bpid: 6,
    mpid: 6,
    name: '渠道分润统计',
    icon: 'database',
    router: '/statistic/agent',
  },
  {
    id: 63,
    bpid: 6,
    mpid: 6,
    name: '对账',
    icon: 'database',
    router: '/statistic/contrast',
  },
  {
    id: 64,
    bpid: 6,
    mpid: 6,
    name: '划账',
    icon: 'database',
    router: '/statistic/remit',
  },
  {
    id: 7,
    bpid: 1,
    name: '物料管理',
    icon: 'qrcode',
    router: '/materials',
  },
  {
    id: 71,
    bpid: 7,
    mpid: 7,
    name: '二维码',
    icon: 'qrcode',
    router: '/materials/qrcode',
  },
  {
    id: 72,
    bpid: 7,
    mpid: 7,
    name: '立板模板',
    icon: 'scan',
    router: '/materials/board',
  },
  {
    id: 2,
    bpid: 1,
    name: '系统管理',
    icon: 'user',
    router: '/setting',
  },
  // {
  //   id: 21,
  //   bpid: 2,
  //   mpid: 2,
  //   name: '角色管理',
  //   icon: 'database',
  //   router: '/setting/role',
  // },
  // {
  //   id: 22,
  //   bpid: 2,
  //   mpid: 2,
  //   name: '用户管理',
  //   icon: 'database',
  //   router: '/setting/user',
  // },
  {
    id: 21,
    bpid: 2,
    mpid: 2,
    name: '职业设置',
    icon: 'database',
    router: '/setting/job',
  },
  // {
  //   id: 24,
  //   mpid: -1,
  //   bpid: 2,
  //   name: '用户详情',
  //   router: '/setting/user/:id',
  // },
  // {
  //   id: 25,
  //   bpid: 2,
  //   mpid: 2,
  //   name: '权限配置',
  //   icon: 'database',
  //   router: '/setting/privilege',
  // },
]
